"""message

Revision ID: 6ef1edb994cf
Revises: 0001_initial_schema
Create Date: 2026-06-01 12:56:00.191529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ef1edb994cf'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
